# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ENV['SECRET_KEY_BASE']
  api_key: 756wwpcnybgkfj
  secret_key: MevJ0KO5RdBA64HE
  oauth_user_token: 8d66422f-62e3-44d2-b583-b38d6ad1ed83
  oauth_user_secret: 2aa8b6ac-6c77-4ba5-a128-5ed70000ec04

test:
  secret_key_base: b6b018e72c8dc75d00652449447ebba56d1c1f46445a8fbfc990dcc647e6a866fe8a7162f408d6c0a6d3f3b7e60845ceddc0ccb7e2cf8a68cafceb718bdb21b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key:	<%= ENV["API_KEY"] %>
  secret_key: <%= ENV["SECRET_KEY"] %>
  oauth_user_token: <%= ENV["OAUTH_USER_OTKEN"]%>
  oauth_user_secret: <%= ENV["OAUTH_USER_SECRET"] %>
